### ISSUE TITLE
Make the Contacts button  of Institute card in Home page functional !

### ISSUE THREAD

**Issue by tonmoy-git** [neo-0007/CampusCommunities#1]
**Feature Request : Add functionality to Contacts button**
- Collect contacts data of Tezpur University
- Prepare a pdf with those contacts
- Upload the pdf to Supabase Backend
- Load that pdf on tapping contacts button

**Comment by neo-0007** [comment]
Okay Tonmoy, create a pdf containing all the official contacts and add it in the attachments !
I will upload it to supabase bucket and connect it with the flutter app .

**Comment by tonmoy-git** [comment]
[NewContacts (1).pdf](https://github.com/user-attachments/files/16532636/NewContacts.1.pdf)

**Comment by tonmoy-git** [comment]
Looking forward for more contributions.

**Comment by neo-0007** [comment]
Thank you for your Contribution !
